apiVersion: apps/v1
kind: Deployment
metadata:
  name: cycle-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cycle
  template:
    metadata:
      labels:
        app: cycle
    spec:
      containers:
      - name: cycle-container
        image: shaikmustafa/cycle
        ports:
        - containerPort: 80
